development:
  adapter: postgresql
  encoding: unicode
  database: tic_tac_toe_rails_development
  pool: 5 
  password:
    
test:
  adapter: postgresql
  encoding: unicode
  database: tic_tac_toe_rails_test
  pool: 5  
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: tic_tac_toe_rails_production
  pool: 5  
  password:
